### ISSUE TITLE
Error reading result file

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#209] opened 2018-06-01 06:59 UTC
OpenModelica and  Dymola can often not open OMSimulator result files. The following error is recieved when attempting to load a result file in OpenModelica

Misslyckades �ppna simuleringsresultat C:/Users/robha67/Documents/OMSim_2018_05_07/CompositeModels/Demonstrator_TLM/Engine_res.mat: Corrupt header: dataInfo matrix

**Comment by lochel** [comment] 2018-06-01 07:48
@robha67 Can you please attach one of the corrupted result files?

**Comment by robha67** [comment] 2018-06-01 11:30
Here are two result files that will not open in Omedit. One is a mat file and that other is specified as a csv via the command oms2_setResultFile("Engine","Engine.csv") 
[CorruptResultFiles.zip](https://github.com/OpenModelica/OMSimulator/files/2062507/CorruptResultFiles.zip)

**Comment by robha67** [comment] 2018-06-01 11:30
I appended two result files in a zip to the issue

/Robert

Från: Lennart Ochel <notifications@github.com>
Skickat: den 1 juni 2018 09:49
Till: OpenModelica/OMSimulator <OMSimulator@noreply.github.com>
Kopia: Robert Hällqvist <robert.hallqvist@liu.se>; Mention <mention@noreply.github.com>
Ämne: Re: [OpenModelica/OMSimulator] Error reading result file (#209)


@robha67<https://github.com/robha67> Can you please attach one of the corrupted result files?

**Comment by meek1** [comment] 2018-06-13 18:49
@robha67 - what's wrong with the csv? It looks OK in Notepad++. The mat-file might be empty?

**Comment by lochel** [comment] 2018-06-19 13:42
I think that can be closed according to our last discussion.

**Comment by meek1** [comment] 2018-10-19 07:58
@lochel, @robbr48, for TLM composite models, the .mat results files for each FMI sub model can still not be opened.

**Comment by meek1** [comment] 2018-10-21 20:38
@lochel, @robbr48, please test using arcsim_FMI_TLM.lua found under T2.2 in the OpenCPS repo. The resulting system_A_res.mat and system_B_res.mat cannot be opened. When running the corresponing native FMI example arcsim_FMI.lua, the result file works.

**Comment by robbr48** [comment] 2018-10-22 12:03
This could be because the FMI models are not deleted with the TLM model. Then the files will never be closed. I guess it does not matter for CSV for some reason, but causes corrupt MAT files.

**Comment by lochel** [comment] 2018-10-22 13:18
@robbr48 Will you take care of it?

**Comment by robbr48** [comment] 2018-10-23 07:41
Strange thing is that it works perfectly for me with the testsuite models on Linux. I will have a look on the test model from @meek1 in Windows and see if I can recreate the problem.

**Comment by robbr48** [comment] 2018-10-23 14:08
@meek1 I cannot simulate the test model because the FMUs require a Dymola license file. Is it possible to export the FMUs without this restriction?

**Comment by meek1** [comment] 2018-10-24 19:40
@robbr48, sorry for the license issue, I'll generate new license free FMUs, but it may take a while. In the mean time, please use the example from @robha67. In the repo: T2.2\Architecture_and_simulation\Simple_model\FineGrainedThermodynamicConnection.zip

This example contains license free windows FMUs and I just reproduced the error with OMSimulator-MSVC. Connot use OMSimulator-GCC because "libwinpthread-1.dll" is missing.

**Comment by lochel** [comment] 2019-01-11 23:07
\*ping\*

**Comment by lochel** [comment] 2019-02-07 20:11
@robbr48 Can we close this ticket?

**Comment by robbr48** [comment] 2019-02-08 10:47
I think so. I believe this was related to oms2.

**Closed** 2019-02-08 11:25 UTC
Labels: bug

**Comment by LorantKupas** [comment] 2019-06-12 14:16
> @robbr48, sorry for the license issue, I'll generate new license free FMUs, but it may take a while. In the mean time, please use the example from @robha67. In the repo: T2.2\Architecture_and_simulation\Simple_model\FineGrainedThermodynamicConnection.zip
> 
> This example contains license free windows FMUs and I just reproduced the error with OMSimulator-MSVC. Connot use OMSimulator-GCC because "libwinpthread-1.dll" is missing.

Hi, 
I am looking for the repo, where can I found it?

**Comment by lochel** [comment] 2019-06-17 09:39
It is the private OpenCPS repository: https://opencps.eu/svn/OPENCPS
