### ISSUE TITLE
Variable names in results file, gets an whitespace added

### ISSUE THREAD

**Issue by Fredrik1Haider** [OpenModelica/OMSimulator#1153] opened 2022-04-19 11:41 UTC
### Steps to reproduce the behavior

Reading the results file (an .csv) with python pandas.read_csv, the variable names contain an additional whitespace and quotation marks in front on the name, comes out as:

`'" model.root.anVariable"'`

Thus, requiring "filtering" to make it consistent with naming in ssm etc.

### Expected behavior

Comes out as:
`'model.root.anVariable'`

### Version and OS

- Version: [`OMSimulator --version`]
- Python: [v3.6]
- OS: [Linux 64bit]

**Comment by arun3688** [comment] 2022-05-06 03:40
@Fredrik1Haider the issue is fixed with this commit https://github.com/OpenModelica/OMSimulator/commit/86bee651f7eebbc1db55a0f6521edcc34478ee21, please test it

**Comment by Fredrik1Haider** [comment] 2022-05-12 12:08
@arun3688 tested and works as requested, thank you!

**Closed** 2022-05-12 12:09 UTC
