### ISSUE TITLE
command line flag ignoreInitialUnknowns does not seem to have effect

### ISSUE THREAD

**Issue by hakan-anderwall** [OpenModelica/OMSimulator#907] opened 2021-01-22 08:48 UTC
### Description
A fmu model simulation generates the output:
"error: ... Erroneous initial unkowns detected in modelDescription.xml"
"info: Use flag ..ignoreInitialUnkowns=true to ignore ..."

Doing so using oms.setCommandLineOption("--ignoreInitialUnkowns=true")
gives the same behavior.

Searching in code for a call to set the return value for ignoreInitialUnknowns shows no existence of a function setting anything, other but the default value (=false). 

### Steps to reproduce the behavior
1. Use a model that has the described behaviour above.
2. Add initialization of command line settings before running simulation:
3. Simulation starts without errors on modelDescription.xml

```Python
oms.setCommandLineOption("--ignoreInitialUnkowns=true")
...
```

### Expected behavior
The simulation starts without these errors when command line option is provided.

### Screenshots
N/A

### Version and OS 
- Version: OMSimulator v2.0.0.post281-g1ce5796-linux
- OS: CentOS 7.9.2009

**Comment by arun3688** [comment] 2021-01-22 09:01
@hakan-anderwall, the flag `--ignoreInitialUnkowns=true` should start the simulation without errors, based on what you wrote on steps to reproduce the problem  `3. Simulation starts without errors on modelDescription.xml`. It seems that simulation works but you get some other error messages, Can you post your error messages, I ran a model with such a behaviour and the simulation works. 

```
oms.setCommandLineOption("--suppressPath=true --ignoreInitialUnknowns=true")
oms.setTempDirectory("./Embrace/")
oms.importFile("Embrace.ssp");
oms.instantiate("model")
oms.initialize("model")
oms.simulate("model")
```

**Comment by robha67** [comment] 2021-01-22 09:08
I tested the "Embrace.ssp" use case (Embrace_trunk\WP3\D3.0\Saab) with version OMSimulator v2.0.0.post279-gc286f9e-win (the latest available nightly build). This model simulates with and without the --ingnoreInitialUnknowns flag in this version. I also tested the same SSP model with the version Håkan is referring to (OMSimulator v2.0.0.post281-g1ce5796-linux) and the model does not work and setting the flag does not make any difference

**Comment by arun3688** [comment] 2021-01-22 09:26
@robha67, Are we using the same ssp we tested for parameter mapping or this is a different ssp, can you send me the ssp to my email

**Comment by robha67** [comment] 2021-01-22 09:28
The error message that I get states: error: [initializeDependencyGraph_initialUnknowns] ECS_SW: Erroneous initial unknowns detected in modelDescription.xml
error: [NewComponent] ECS_HW: Couldn't initialize  dependency graph for initial unknowns
info: Use flag --ignoreInitialUnknows

And yes. I tried to reproduce th error using this ssp and something seems strange

**Comment by hakan-anderwall** [comment] 2021-01-22 09:58
[simulation_log_1.txt](https://github.com/OpenModelica/OMSimulator/files/5854986/simulation_log_1.txt)
Attaching part o log output. The same for both using the flag and not using it.
As said a quick code review showed no trace of using the flag as for another cmd line option (InputExtrapolation)

**Comment by arun3688** [comment] 2021-01-22 10:09
@hakan-anderwall myself and @robha had short meeting via teams, and the example with the same behaviour  which is in the Embrace trunk `Embrace_trunk\WP3\D3.0\Saab`, `Embrace.ssp` works with the latest OMSimulator version `OMSimulator v2.0.0.post281-g1ce5796`

Based on your attached log `simulation_log_1.txt`, i can see the following information
```
Thu Jan 21 16:36:23 2021 | info:    Initializing logging (OMSimulator v2.0.0.post281-g1ce5796-linux)
Thu Jan 21 16:36:23 2021 | info:    New model "model" with corresponding temp directory "/path/simulation_output/tmp/model-y2inkmrk"
...
Thu Jan 21 16:36:23 2021 | warning: xx: Variable T_filt.y with index 5937 is not an initial unknown.

Thu Jan 21 16:36:23 2021 | error:   [initializeDependencyGraph_initialUnknowns] xx: Erroneous initial unknowns detected in modelDescription.xml.
Thu Jan 21 16:36:23 2021 | info:    Use flag --ignoreInitialUnknowns=true to ignore all initial unknowns, but this can cause inflated loop size.
Thu Jan 21 16:36:23 2021 | error:   [NewComponent] xx: Couldn't initialize dependency graph for initial unknowns.
```

You are still not using the flag `--ignoreInitialUnknowns=true` in your python script

**Comment by robha67** [comment] 2021-01-22 10:24
The issue is solved. Turns out the the flag was too late in the python script. Thank you Arunkumar for your help

**Comment by lochel** [comment] 2021-01-22 10:25
Thanks @robha67. Is there anything to improve or should we just close this issue?

**Comment by robha67** [comment] 2021-01-22 10:26
This issue can be closed

**Closed** 2021-01-22 10:29 UTC

**Comment by arun3688** [comment] 2021-03-25 10:29
@robha67 This PR https://github.com/OpenModelica/OMSimulator/pull/996 fixes the ignoreInitialUnkowns problems
