### ISSUE TITLE
Broken installation using CMake for Linux

### ISSUE THREAD

**Issue by hakan-anderwall** [OpenModelica/OMSimulator#908] opened 2021-01-22 09:28 UTC
### Description
Can not use the install instructions on github to make a standalone installation for Linux, several patches needed

### Steps to reproduce the behavior
generated CMake scripts in link.txt files uses  /bin/c++ which on my system is a non-shared gcc-4.8.5 installation
This means that builtin linker scripts do not have shared library paths.
I would like my c++ binary defined fiorst on path which is a much new gcc to be used.
Now I need to patch some link.txt generated by CMAke with -L/path/to/gcc/shared/installation/lib  for linking the libraries.

I also need to in /abs/path/to/build/lib create symlinks to:
- libomtlmsimulator.so
- libOMSimulator.so
- OMSimulator(?)

and I also need to in /abs/path/to/build/bin create symlinks to:
- OMSimulator
- OMSimulatorPython3

```bash
pushd OMSimulator
make config-3rdParty
make config.OMSimulator
export OMBUILDDIR= /abs/path/to/build
make OMSimulator -j7
# ** link error and then patches as described above
...
```

### Expected behavior
Clean install process with installation bin and lib in $OMBUILDDIR

### Screenshots
N/A

### Version and OS
- Version: OMSimulator v2.0.0.post281-g1ce5796-linux
- OS: CentOS 7.9.2009

**Comment by lochel** [comment] 2021-01-22 10:32
Can you provide a pull request with your changes?

**Comment by AnHeuermann** [comment] 2021-02-12 11:37
I'll see if I can reproduce your issue in a docker with CentOS7.

**Comment by lochel** [comment] 2021-02-12 12:21
I can confirm that there is some linking problem when executing the commands as stated above:

```
> make config-3rdParty -j5
> make config-OMSimulator
> export OMBUILDDIR=/abs/path/to/build
> make OMSimulator -j5
[...]
/usr/bin/ld: cannot find -lomtlmsimulator
collect2: error: ld returned 1 exit status
```

Defining `OMBUILDDIR` already before configuring the repository solves that issue at least:
```
> export OMBUILDDIR=/abs/path/to/build
> make config-3rdParty -j5
> make config-OMSimulator
> make OMSimulator -j5
```

Everything got installed into `/abs/path/to/build` and I hadn't to create any symlinks or other workarounds to execute OMSimulator.

I couldn't test the other issue related to "non-shared gcc-4.8.5 installation" though. I hope @AnHeuermann can have a look usig some docker images.

**Comment by AnHeuermann** [comment] 2021-02-16 10:28
I used the dockerfile from .CI/centos7 to run:

```bash
$ docker run --rm -it -v $(pwd):/OMSimulator omsimulator-build-deps:centos7 bash
# cd /OMSimulator/
# mkdir -p /OMSimulatorPath/to/build
# export OMBUILDDIR=/OMSimulatorPath/to/build // No space after '='
# make config-3rdParty -j16 &> config-3rdParty.log
# make config-OMSimulator &> config-OMSimulator.log
# make OMSimulator -j16 &> build-OMSimulator.log
```

Then everything was installed to `/OMSimulatorPath/to/build/bin/OMSimulator`. So indeed the solution is to just specify `OMBUILDDIR` before starting configure.

Since I can't reproduce the error (or @lochel's solution is working) I'm closing this issue. If there are still problems please reopen this issue.

**Closed by AnHeuermann** 2021-02-16 10:28 UTC
